# Accessing/Changing specific elements, rows, columns, etc

In [1]:
import numpy as np

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])


# Get a specific elements ([r, c])

In [13]:
a[1, 5]

13

# Get a specific row

In [15]:
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

# Get a specific column

In [17]:
a[:, 0]

array([1, 8])

# Getting a little more fancy [startindec:endindex:stepsize]

In [21]:
a[0, 1:6:2]

array([2, 4, 6])

# Changing elements

In [22]:
a[1,5] = 20
print(a)

18

In [24]:
#a[:, 2] = 5
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 18 14]]


# A 3-D example

In [33]:
b = np.array([[[1,2], [3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


# Get specific element from a 3-D array

In [36]:
b[:, 1 , :] = [[9,9]]
print(b)

[[[1 2]
  [9 9]
  [5 6]
  [7 8]]]
