# Initializing Different Types of Arrays

In [1]:
import numpy as np

In [5]:
# All 0s matrx
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
# All 1s matrix

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((4,3,2), dtype="int32")

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [14]:
# Any other number
np.full((2,2), 99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [18]:
# Any other number (full_like)
a = np.array([[1,2], [3,4], [5,6]])
np.full_like(a, 888)

array([[888, 888],
       [888, 888],
       [888, 888]])

In [20]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.89192   , 0.74679256, 0.24750029],
        [0.02814393, 0.99941912, 0.99945926]],

       [[0.09578761, 0.65925086, 0.41623639],
        [0.13953795, 0.55940968, 0.93799371]],

       [[0.93316973, 0.19216184, 0.32670553],
        [0.62732021, 0.42319456, 0.55907071]],

       [[0.97705222, 0.59955641, 0.90775389],
        [0.80858692, 0.17798309, 0.89911627]]])

In [21]:
# with shape
np.random.random_sample(a.shape)

array([[0.57692032, 0.86585532],
       [0.66985064, 0.0727392 ],
       [0.05774318, 0.25182095]])

In [28]:
# Random Integer values
np.random.randint(-3, 8, size=(3,3))

array([[ 5,  3,  0],
       [ 0,  4,  2],
       [-2,  5,  5]])

In [29]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [44]:
output = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

output[1:4, 1:4] = z

print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays!!!

In [47]:
a = np.array([1,2,3])
b= a
b[0] = 100

a

array([100,   2,   3])