# Load in Numpy (Remember to pip install numpy if you haven't)

In [1]:
import numpy as np

# The Basics

In [2]:
a = np.array([1,2,3], dtype="int32")
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


# Get Dimension

In [4]:
# a.ndim
b.ndim


2

# Get Shape

In [5]:
a.shape

(3,)

In [6]:
b.shape

(2, 3)

# Get Type

In [7]:
a.dtype

dtype('int32')

# Get Size 

In [8]:
a.itemsize

4

In [9]:
b.itemsize

8

# Get  total size

In [12]:
#a.size * a.itemsize

# a.size gives the total number of elements whilst a.itemsize gives the size of each element

a.nbytes



12