In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a += 5
print(a)

[6 7 8 9]


In [4]:
a + 2

array([ 8,  9, 10, 11])

In [5]:
a * 2

array([12, 14, 16, 18])

In [6]:
a / 2

array([3. , 3.5, 4. , 4.5])

In [7]:
a % 2

array([0, 1, 0, 1], dtype=int32)

In [10]:
b = np.array([1,0,1,0])
c = np.array([2,4,5,6])
b + c

array([3, 4, 6, 6])

In [11]:
c ** 2

array([ 4, 16, 25, 36])

# Take the `sin` of all values

In [12]:
np.sin(c)

array([ 0.90929743, -0.7568025 , -0.95892427, -0.2794155 ])

In [14]:
np.cos(c)

array([-0.41614684, -0.65364362,  0.28366219,  0.96017029])

In [ ]:
# for a lot more (http://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [18]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]


array([[6., 6.],
       [6., 6.]])

In [21]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)


1.0

In [20]:
# for a lot more (http://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular vector decomposition
# Eigenvalues
# Matri Norm
# Inverse 
# Etc ...

1.0